# GitLab CI/CD Configuration for Abkhazia

# Global setup that runs before all jobs
before_script:
  # Load required modules on the Oberon cluster
  - module load anaconda/3 espeak/1.49.2 festival/2.4 shorten/3.6.1

# Build stage: Create and configure the environment, then install Abkhazia
abkhazia-build:
  stage: build
  script:
    # Create a Python virtual environment for testing (if not already existing)
    - conda create --name abkhazia-ci python=3 2> /dev/null || true
    - conda activate abkhazia-ci
    
    # Configure and install Abkhazia with dependencies
    - KALDI_PATH=/shared/apps/abkhazia/kaldi ./configure
    - pip install coverage pytest
    - python setup.py build
    - python setup.py install

# Test stage: Run the test suite
abkhazia-test:
  stage: test
  script:
    - conda activate abkhazia-ci
    - ABKHAZIA_BUCKEYE=/scratch2/mbernard/ci/abkhazia_test_corpus pytest -v test

# Deploy stage: Update the master installation when changes are merged to master
abkhazia-deploy:
  stage: deploy
  only:
    refs:
      - master
  script:
    - conda activate abkhazia
    - cd /shared/apps/abkhazia
    - git pull origin master
    - python setup.py build
    - python setup.py install

# Documentation stage: Build and publish documentation when changes are merged to master
# Documentation is available at https://docs.cognitive-ml.fr/abkhazia
documentation:
  stage: deploy
  only:
    refs:
      - master
  script:
    - module load texlive/2018
    - conda activate abkhazia-ci
    - pip install sphinx_rtd_theme
    - sphinx-build docs/source docs/build
    - scp -r docs/build/* cognitive-ml.fr:/var/www/docs.cognitive-ml.fr/abkhazia
